'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
    en: {
        // Navbar
        'nav.home': 'Home',
        'nav.about': 'About',
        'nav.training': 'Training Mode',
        'nav.contact': 'Contact',
        'nav.signin': 'Sign In',
        'nav.getstarted': 'Get Started',
        'nav.notifications': 'Notifications',
        'nav.messages': 'Messages',
        'nav.profile': 'User profile',
        'nav.dashboard': 'Dashboard',
        'nav.signout': 'Sign Out',

        // Roles
        'role.jobseeker': 'Job Seeker',
        'role.clinic': 'Clinic',
        'role.admin': 'Admin',

        // Training
        'training.exit': 'Exit Training Mode',
        'training.back': 'Back to Training',
        'training.master': 'Master Dental Assisting Skills',
        'training.description': 'Comprehensive training courses with videos, images, and interactive content to help you become a skilled dental assistant',
        'training.categories': 'Training Categories',
        'training.featured': 'Featured Courses',
        'training.viewall': 'View All',

        // AI Assistant
        'ai.title': 'AI Assistant',
        'ai.learning': 'Always learning',
        'ai.placeholder': 'Ask me anything...',
        'ai.powered': 'AI-powered • Learns from interactions',

        // Home Page
        'home.hero.title.prefix': 'Find Your Perfect',
        'home.hero.title.suffix': 'Match',
        'home.hero.title.highlight': 'Dental Career',
        'home.hero.description': 'Connect with top dental clinics and professionals. Build your CV, get smart matches, and land your dream job in the dental industry.',
        'home.hero.badge': '#1 Dental Job Platform',
        'home.hero.btn.seeker': "I'm Looking for Work",
        'home.hero.btn.clinic': "I'm Hiring",
        'home.trust.free': 'Free to join',
        'home.trust.nocred': 'No credit card',
        'home.trust.cancel': 'Cancel anytime',

        'home.stats.seekers': 'Job Seekers',
        'home.stats.clinics': 'Dental Clinics',
        'home.stats.match': 'Match Success',
        'home.stats.response': 'Avg. Response',

        'home.features.title.prefix': 'Everything You Need to',
        'home.features.title.highlight': 'Succeed',
        'home.features.subtitle': 'Powerful tools designed specifically for dental professionals and clinics.',
        'home.features.cv.title': 'Smart CV Builder',
        'home.features.cv.desc': 'Create a professional dental CV in minutes with our guided wizard. No design skills needed.',
        'home.features.match.title': 'Smart Matching',
        'home.features.match.desc': 'Our AI-powered algorithm matches you with jobs that fit your skills, location, and salary expectations.',
        'home.features.verified.title': 'Verified Profiles',
        'home.features.verified.desc': 'All profiles are verified to ensure quality connections between candidates and employers.',
        'home.features.privacy.title': 'Privacy First',
        'home.features.privacy.desc': 'Control who sees your profile. Only share your CV with employers you choose.',

        'home.how.title': 'How It Works',
        'home.how.subtitle': 'Get started in 3 simple steps',
        'home.how.step1.title': 'Create Your Profile',
        'home.how.step1.desc': 'Sign up and build your professional dental CV using our smart wizard.',
        'home.how.step2.title': 'Get Matched',
        'home.how.step2.desc': 'Our algorithm finds the best opportunities based on your preferences.',
        'home.how.step3.title': 'Connect & Hire',
        'home.how.step3.desc': 'Chat directly with employers and land your dream dental job.',
        'home.cta.button': 'Get Started Free',

        'home.jobs.title': 'Popular Job Categories',
        'home.jobs.subtitle': 'Explore opportunities in the dental industry',
        'home.jobs.viewall': 'View all jobs',
        'home.jobs.assistant': 'Dental Assistant',
        'home.jobs.hygienist': 'Dental Hygienist',
        'home.jobs.ortho': 'Orthodontic Assistant',
        'home.jobs.sales': 'Dental Sales Rep',
        'home.jobs.open': 'open positions',

        'home.testimonials.title.prefix': 'Trusted by Dental',
        'home.testimonials.title.highlight': 'Professionals',
        'home.testimonials.subtitle': 'See what our users have to say about DentalHire',

        'home.final.title': 'Ready to Find Your Perfect Match?',
        'home.final.subtitle': 'Join thousands of dental professionals who found their dream careers through Hire Me.',
        'home.final.btn.create': 'Create Free Account',
        'home.final.btn.post': 'Post a Job',

        // Auth - Login
        'auth.welcome': 'Welcome back',
        'auth.signin.subtitle': 'Sign in to your account to continue',
        'auth.email': 'Email',
        'auth.password': 'Password',
        'auth.remember': 'Remember me',
        'auth.forgot': 'Forgot password?',
        'auth.signin': 'Sign In',
        'auth.or': 'Or continue with',
        'auth.noaccount': "Don't have an account?",
        'auth.createfree': 'Create one for free',
        'auth.loginfailed': 'Login failed',

        // Auth - Register
        'auth.createaccount': 'Create your account',
        'auth.almostthere': 'Almost there!',
        'auth.choosetype': 'Choose your account type to get started',
        'auth.filldetails': 'Fill in your details to complete registration',
        'auth.role': 'Role',
        'auth.account': 'Account',
        'auth.iwantto': 'I want to',
        'auth.iama': 'I am a',
        'auth.jobseeker': 'Job Seeker',
        'auth.jobseeker.desc': 'Looking for dental job opportunities',
        'auth.clinic': 'Clinic / Employer',
        'auth.clinic.desc': 'Hiring dental professionals',
        'auth.assistant': 'Dental Assistant',
        'auth.assistant.desc': 'Clinic staff & assistants',
        'auth.salesrep': 'Sales Representative',
        'auth.salesrep.desc': 'Dental equipment & supply sales',
        'auth.dentalclinic': 'Dental Clinic',
        'auth.dentalclinic.desc': 'Practice looking to hire',
        'auth.dentist': 'Individual Dentist',
        'auth.dentist.desc': 'Dentist hiring for practice',
        'auth.continue': 'Continue',
        'auth.firstname': 'First Name',
        'auth.lastname': 'Last Name',
        'auth.confirmpassword': 'Confirm Password',
        'auth.agreeto': 'I agree to the',
        'auth.terms': 'Terms of Service',
        'auth.and': 'and',
        'auth.privacy': 'Privacy Policy',
        'auth.back': 'Back',
        'auth.createaccount.btn': 'Create Account',
        'auth.haveaccount': 'Already have an account?',
        'auth.registerfailed': 'Registration failed',

        // About Page
        'about.title': 'About',
        'about.subtitle': 'Connecting talented dental professionals with leading clinics across the region',
        'about.mission': 'Our Mission',
        'about.mission.p1': 'Hire Me is dedicated to revolutionizing the way dental professionals find their dream jobs and how clinics discover exceptional talent.',
        'about.mission.p2': 'We believe in creating meaningful connections that benefit both job seekers and employers, fostering growth and excellence in the dental industry.',
        'about.whyus': 'Why Choose Us?',
        'about.whyus.1': 'Specialized platform for dental professionals',
        'about.whyus.2': 'Smart matching algorithm',
        'about.whyus.3': 'Verified clinics and candidates',
        'about.whyus.4': 'Easy application process',
        'about.values': 'Our Values',
        'about.community': 'Community',
        'about.community.desc': 'Building a supportive network of dental professionals',
        'about.excellence': 'Excellence',
        'about.excellence.desc': 'Committed to the highest standards in recruitment',
        'about.trust': 'Trust',
        'about.trust.desc': 'Verified profiles and transparent processes',
        'about.cta': 'Ready to Get Started?',
        'about.cta.desc': 'Join thousands of dental professionals and clinics already using Hire Me',
        'about.cta.btn': 'Create Your Account',

        // Contact Page
        'contact.title': 'Get in Touch',
        'contact.subtitle': "Have questions? We'd love to hear from you",
        'contact.form.title': 'Send us a Message',
        'contact.name': 'Name',
        'contact.name.placeholder': 'Your name',
        'contact.email': 'Email',
        'contact.email.placeholder': 'your.email@example.com',
        'contact.subject': 'Subject',
        'contact.subject.placeholder': 'How can we help?',
        'contact.message': 'Message',
        'contact.message.placeholder': 'Tell us more...',
        'contact.send': 'Send Message',
        'contact.info.title': 'Contact Information',
        'contact.info.subtitle': "Reach out to us through any of these channels and we'll get back to you as soon as possible.",
        'contact.phone': 'Phone',
        'contact.office': 'Office',
        'contact.help': 'Need Immediate Help?',
        'contact.help.desc': 'Check out our FAQ section for quick answers to common questions.',
        'contact.faq': 'View FAQ',

        // Footer
        'footer.desc': 'Connecting dental professionals with their perfect career opportunities since 2020.',
        'footer.company': 'Company',
        'footer.aboutus': 'About Us',
        'footer.careers': 'Careers',
        'footer.press': 'Press',
        'footer.blog': 'Blog',
        'footer.forjobseekers': 'For Job Seekers',
        'footer.browsejobs': 'Browse Jobs',
        'footer.createcv': 'Create CV',
        'footer.resources': 'Career Resources',
        'footer.salary': 'Salary Guide',
        'footer.foremployers': 'For Employers',
        'footer.postjob': 'Post a Job',
        'footer.searchcandidates': 'Search Candidates',
        'footer.pricing': 'Pricing',
        'footer.employerresources': 'Employer Resources',
        'footer.support': 'Support',
        'footer.helpcenter': 'Help Center',
        'footer.contactus': 'Contact Us',
        'footer.privacypolicy': 'Privacy Policy',
        'footer.termsofservice': 'Terms of Service',
        'footer.copyright': 'Hire Me. All rights reserved.',

        // Jobs Page
        'jobs.title': 'Find Your Dream Dental Job',
        'jobs.subtitle': 'Browse through hundreds of dental positions from top clinics',
        'jobs.search': 'Search jobs...',
        'jobs.location': 'Location',
        'jobs.type': 'Job Type',
        'jobs.fulltime': 'Full-time',
        'jobs.parttime': 'Part-time',
        'jobs.contract': 'Contract',
        'jobs.apply': 'Apply Now',
        'jobs.save': 'Save Job',
        'jobs.posted': 'Posted',
        'jobs.daysago': 'days ago',
        'jobs.noresults': 'No jobs found matching your criteria',

        // Dashboard Common
        'dashboard.welcome': 'Welcome back',
        'dashboard.welcomesubtitle': "Here's what's happening with your job search",
        'dashboard.overview': 'Overview',
        'dashboard.recentactivity': 'Recent Activity',
        'dashboard.recentactivity.subtitle': 'Your latest profile interactions',
        'dashboard.viewall': 'View All',
        'dashboard.applications': 'Applications',
        'dashboard.messages': 'Messages',
        'dashboard.profile': 'Profile',
        'dashboard.settings': 'Settings',
        'dashboard.editcv': 'Edit CV',
        'dashboard.completecv': 'Complete your CV to get more matches',
        'dashboard.profilecomplete': 'Your profile is',
        'dashboard.complete': 'complete',
        'dashboard.completenow': 'Complete Now',
        'dashboard.profileviews': 'Profile Views',
        'dashboard.matchscore': 'Match Score',
        'dashboard.thisweek': 'this week',
        'dashboard.yourmatchscore': 'Your Match Score',
        'dashboard.matchdesc': 'Great! Your profile matches well with most employer preferences.',
        'dashboard.skills': 'Skills',
        'dashboard.experience': 'Experience',
        'dashboard.location': 'Location',
        'dashboard.improvescore': 'Improve Score',
        'dashboard.recommended': 'Recommended for You',
        'dashboard.recommended.subtitle': 'Jobs that match your profile',
        'dashboard.hoursago': 'hours ago',
        'dashboard.dayago': 'day ago',
        'dashboard.saved': 'Saved Jobs',

        // Sidebar
        'sidebar.dashboard': 'Dashboard',
        'sidebar.cvbuilder': 'CV Builder',
        'sidebar.myprofile': 'My Profile',
        'sidebar.applications': 'Applications',
        'sidebar.applications.employer': 'Applicant Requests',
        'sidebar.messages': 'Messages',
        'sidebar.settings': 'Settings',
        'sidebar.findjobs': 'Find Jobs',
        'sidebar.findcandidates': 'Find Candidates',
        'sidebar.jobpostings': 'Job Postings',
        'sidebar.savedcandidates': 'Saved Candidates',
        'sidebar.clinicprofile': 'Clinic Profile',
        'sidebar.manageusers': 'Manage Users',
        'sidebar.managecvs': 'Manage CVs',
        'sidebar.manageclinics': 'Manage Clinics',
        'sidebar.analytics': 'Analytics',
        'sidebar.moderation': 'Moderation',
        'sidebar.help': 'Help & Support',
        'sidebar.signout': 'Sign Out',

        // CV Builder
        'cv.title': 'CV Builder',
        'cv.subtitle': 'Create your professional dental CV in minutes',
        'cv.savedraft': 'Save Draft',
        'cv.preview': 'Preview',
        'cv.progress': 'Progress',
        'cv.complete': 'Complete',
        'cv.previous': 'Previous',
        'cv.continue': 'Continue',
        'cv.skip': 'Skip',
        'cv.completecv': 'Complete CV',
        'cv.step': 'Step',
        'cv.of': 'of',
        'cv.optional': 'Optional',

        // CV Steps
        'cv.step.personal': 'Personal Info',
        'cv.step.personal.desc': 'Basic information',
        'cv.step.experience': 'Experience',
        'cv.step.experience.desc': 'Work history',
        'cv.step.skills': 'Skills',
        'cv.step.skills.desc': 'Your abilities',
        'cv.step.certifications': 'Certifications',
        'cv.step.certifications.desc': 'Credentials (Optional)',
        'cv.step.languages': 'Languages',
        'cv.step.languages.desc': 'Languages spoken',
        'cv.step.salary': 'Salary',
        'cv.step.salary.desc': 'Expectations',
        'cv.step.location': 'Location',
        'cv.step.location.desc': 'Preferences',
        'cv.step.availability': 'Availability',
        'cv.step.availability.desc': 'Schedule',
        'cv.step.documents': 'Documents',
        'cv.step.documents.desc': 'Optional files (Optional)',

        // Personal Info Form
        'cv.personal.intro': "Let's start with your basic information. This will appear at the top of your CV.",
        'cv.personal.fullname': 'Full Name',
        'cv.personal.fullname.placeholder': 'John Doe',
        'cv.personal.email': 'Email Address',
        'cv.personal.email.placeholder': 'john@example.com',
        'cv.personal.phone': 'Phone Number',
        'cv.personal.phone.placeholder': '+1 (555) 123-456',
        'cv.personal.city': 'City',
        'cv.personal.city.placeholder': 'Los Angeles',
        'cv.personal.gender': 'Gender',
        'cv.personal.gender.select': 'Select gender',
        'cv.personal.gender.male': 'Male',
        'cv.personal.gender.female': 'Female',
        'cv.personal.gender.other': 'Other',
        'cv.personal.gender.prefer': 'Prefer not to say',
        'cv.personal.dob': 'Date of Birth',
        'cv.personal.address': 'Street Address',
        'cv.personal.address.placeholder': 'Main Street 123',
        'cv.personal.nationality': 'Nationality',
        'cv.personal.nationality.placeholder': 'American',
        'cv.personal.bio': 'Professional Bio',
        'cv.personal.bio.placeholder': 'Write a brief summary about yourself, your career goals, and what makes you a great candidate...',
        'cv.personal.photo': 'Profile Photo',
        'cv.personal.upload': 'Upload Photo',
        'cv.personal.photoinfo': 'JPG, PNG or WebP. Max 2MB.',
        'cv.personal.tip': 'A complete profile with a professional photo increases your chances of getting noticed by employers.',
        'cv.personal.characters': 'characters',

        // Experience Form
        'cv.exp.intro': 'Add your work experience. Start with your most recent position.',
        'cv.exp.add': 'Add Work Experience',
        'cv.exp.edit': 'Edit Experience',
        'cv.exp.addnew': 'Add Experience',
        'cv.exp.jobtitle': 'Job Title',
        'cv.exp.jobtitle.placeholder': 'Dental Assistant',
        'cv.exp.company': 'Company',
        'cv.exp.company.placeholder': 'Smile Dental Clinic',
        'cv.exp.location': 'Location',
        'cv.exp.location.placeholder': 'Los Angeles, CA',
        'cv.exp.current': 'I currently work here',
        'cv.exp.startdate': 'Start Date',
        'cv.exp.enddate': 'End Date',
        'cv.exp.description': 'Description',
        'cv.exp.description.placeholder': 'Describe your responsibilities and achievements...',
        'cv.exp.present': 'Present',
        'cv.exp.update': 'Update',
        'cv.exp.note': 'Adding at least one work experience helps employers understand your background and increases your match score.',

        // Skills Form
        'cv.skills.intro': 'Select skills that match your expertise. Add at least 3 skills to improve your match score.',
        'cv.skills.selected': 'Selected Skills',
        'cv.skills.noselected': 'No skills selected yet. Choose from suggestions below or add your own.',
        'cv.skills.addmore': 'Add at least {count} more skill(s) to continue.',
        'cv.skills.search': 'Search Skills',
        'cv.skills.searchplaceholder': 'Type to search skills...',
        'cv.skills.addcustom': 'Add Custom Skill',
        'cv.skills.customplaceholder': 'Enter a skill not listed above',
        'cv.skills.popular': 'Popular Dental Skills',
        'cv.skills.allavailable': 'All Available Skills',

        // Common
        'common.loading': 'Loading...',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.close': 'Close',
        'common.search': 'Search',
        'common.filter': 'Filter',
        'common.viewmore': 'View More',
        'common.learnmore': 'Learn More',
        'common.tip': 'Tip',
        'common.note': 'Note',
        'common.add': 'Add',
        // Admin Dashboard
        'admin.dashboard': 'Admin Dashboard',
        'admin.subtitle': 'Platform overview and management',
        'admin.stats.users': 'Total Users',
        'admin.stats.jobseekers': 'Job Seekers',
        'admin.stats.clinics': 'Clinics',
        'admin.stats.activecvs': 'Active CVs',
        'admin.recentusers': 'Recent Users',
        'admin.recentusers.subtitle': 'Latest registrations on the platform',
        'admin.pending': 'Pending Approvals',
        'admin.pending.subtitle': 'Items requiring attention',
        'admin.viewall': 'View All',
        'admin.viewallpending': 'View All Pending',
        'admin.matches': 'Matches This Month',
        'admin.activejobseekers': 'Active Job Seekers',
        'admin.newusers': 'New Users This Week',
        'admin.export': 'Export Report',
        'admin.adduser': 'Add User',
        'admin.table.user': 'User',
        'admin.table.type': 'Type',
        'admin.table.status': 'Status',
        'admin.table.registered': 'Registered',
        'admin.thismonth': 'this month',

        // Admin Users Page
        'admin.users.title': 'User Management',
        'admin.users.subtitle': 'Manage all users, verify accounts, and review documents.',
        'admin.users.export': 'Export',
        'admin.users.add': 'Add User',
        'admin.users.search': 'Search by name or email...',
        'admin.users.filter.role': 'All Roles',
        'admin.users.filter.jobseeker': 'Job Seekers',
        'admin.users.filter.clinic': 'Clinics',
        'admin.users.filter.admin': 'Admins',
        'admin.users.filter.status': 'All Status',
        'admin.users.filter.verified': 'Verified',
        'admin.users.filter.unverified': 'Unverified',
        'admin.users.table.user': 'User',
        'admin.users.table.role': 'Role',
        'admin.users.table.verification': 'Verification',
        'admin.users.table.docs': 'Documents',
        'admin.users.table.joined': 'Joined',
        'admin.users.table.actions': 'Actions',
        'admin.users.docs.review': 'Review',
        'admin.users.docs.title': 'Documents',
        'admin.users.docs.no_docs': 'No documents uploaded by this user.',
        'admin.users.docs.view': 'View',
        'admin.users.docs.approve': 'Approve & Verify User',
        'admin.users.delete.confirm': 'Are you sure you want to delete this user? This action cannot be undone.',
        'admin.users.delete.error': 'Failed to delete user',
        'admin.users.verify.error': 'Error updating verification',
        'admin.users.loading': 'Loading users...',
        'admin.users.nousers': 'No users found.',
        'admin.users.permission_denied': 'Permission denied. Please Sign Out and Sign In again to refresh your Admin key.',
    },
    ar: {
        // Navbar
        'nav.home': 'الرئيسية',
        'nav.about': 'عن التطبيق',
        'nav.training': 'وضع التدريب',
        'nav.contact': 'اتصل بنا',
        'nav.signin': 'تسجيل الدخول',
        'nav.getstarted': 'ابدأ الآن',
        'nav.notifications': 'الإشعارات',
        'nav.messages': 'الرسائل',
        'nav.profile': 'الملف الشخصي',
        'nav.dashboard': 'لوحة التحكم',
        'nav.signout': 'تسجيل الخروج',

        // Roles
        'role.jobseeker': 'باحث عن عمل',
        'role.clinic': 'عيادة',
        'role.admin': 'مدير',

        // Training
        'training.exit': 'الخروج من وضع التدريب',
        'training.back': 'العودة للتدريب',
        'training.master': 'إتقان مهارات مساعد طبيب الأسنان',
        'training.description': 'دورات تدريبية شاملة مع فيديوهات وصور ومحتوى تفاعلي لمساعدتك على أن تصبح مساعد أسنان ماهر',
        'training.categories': 'فئات التدريب',
        'training.featured': 'الدورات المميزة',
        'training.viewall': 'عرض الكل',

        // AI Assistant
        'ai.title': 'المساعد الذكي',
        'ai.learning': 'يتعلم دائماً',
        'ai.placeholder': 'اسألني أي شيء...',
        'ai.powered': 'مدعوم بالذكاء الاصطناعي • يتعلم من التفاعلات',

        // Home Page
        'home.hero.title.prefix': 'اعثر على',
        'home.hero.title.suffix': 'المثالي',
        'home.hero.title.highlight': 'مسارك المهني',
        'home.hero.description': 'تواصل مع أفضل عيادات الأسنان والمحترفين. أنشئ سيرتك الذاتية، احصل على وظائف تناسبك، وابدأ رحلة نجاحك في عالم طب الأسنان.',
        'home.hero.badge': 'المنصة الأولى لتوظيف الأسنان',
        'home.hero.btn.seeker': 'أبحث عن عمل',
        'home.hero.btn.clinic': 'أريد موظفين',
        'home.trust.free': 'انضم مجاناً',
        'home.trust.nocred': 'بدون بطاقة ائتمان',
        'home.trust.cancel': 'إلغاء في أي وقت',

        'home.stats.seekers': 'باحث عن عمل',
        'home.stats.clinics': 'عيادة أسنان',
        'home.stats.match': 'نسبة التطابق',
        'home.stats.response': 'سرعة الرد',

        'home.features.title.prefix': 'كل ما تحتاجه',
        'home.features.title.highlight': 'للنجاح',
        'home.features.subtitle': 'أدوات قوية صممت خصيصاً لمحترفي الأسنان والعيادات.',
        'home.features.cv.title': 'باني السيرة الذاتية الذكي',
        'home.features.cv.desc': 'أنشئ سيرة ذاتية احترافية في دقائق مع معالجنا الذكي. لا تحتاج لمهارات تصميم.',
        'home.features.match.title': 'المطابقة الذكية',
        'home.features.match.desc': 'خوارزمياتنا المدعومة بالذكاء الاصطناعي تطابقك مع الوظائف التي تناسب مهاراتك وموقعك.',
        'home.features.verified.title': 'ملفات موثقة',
        'home.features.verified.desc': 'يتم التحقق من جميع الملفات لضمان جودة التواصل بين المرشحين وأصحاب العمل.',
        'home.features.privacy.title': 'الخصوصية أولاً',
        'home.features.privacy.desc': 'تحكم في من يرى ملفك الشخصي. شارك سيرتك الذاتية فقط مع أصحاب العمل الذين تختارهم.',

        'home.how.title': 'كيف يعمل التطبيق',
        'home.how.subtitle': 'ابدأ في 3 خطوات بسيطة',
        'home.how.step1.title': 'أنشئ ملفك الشخصي',
        'home.how.step1.desc': 'سجل حسابك وابنِ سيرتك الذاتية الاحترافية باستخدام معالجنا الذكي.',
        'home.how.step2.title': 'احصل على المطابقات',
        'home.how.step2.desc': 'خوارزمياتنا تجد لك أفضل الفرص بناءً على تفضيلاتك.',
        'home.how.step3.title': 'تواصل وتوظف',
        'home.how.step3.desc': 'تحدث مباشرة مع أصحاب العمل واحصل على وظيفة أحلامك.',
        'home.cta.button': 'ابدأ مجاناً',

        'home.jobs.title': 'فئات الوظائف الشائعة',
        'home.jobs.subtitle': 'استكشف الفرص في مجال طب الأسنان',
        'home.jobs.viewall': 'عرض كل الوظائف',
        'home.jobs.assistant': 'مساعد طبيب أسنان',
        'home.jobs.hygienist': 'أخصائي صحة أسنان',
        'home.jobs.ortho': 'مساعد تقويم أسنان',
        'home.jobs.sales': 'مندوب مبيعات أسنان',
        'home.jobs.open': 'وظيفة متاحة',

        'home.testimonials.title.prefix': 'موثوق من قبل',
        'home.testimonials.title.highlight': 'المحترفين',
        'home.testimonials.subtitle': 'شاهد ما يقوله مستخدمونا عن Hire Me',

        'home.final.title': 'مستعد للعثور على وظيفتك المثالية؟',
        'home.final.subtitle': 'انضم لآلاف المحترفين الذين وجدوا وظائف أحلامهم عبر Hire Me.',
        'home.final.btn.create': 'أنشئ حساب مجاني',
        'home.final.btn.post': 'أعلن عن وظيفة',

        // Auth - Login
        'auth.welcome': 'مرحباً بعودتك',
        'auth.signin.subtitle': 'سجل دخول لحسابك للمتابعة',
        'auth.email': 'البريد الإلكتروني',
        'auth.password': 'كلمة المرور',
        'auth.remember': 'تذكرني',
        'auth.forgot': 'نسيت كلمة المرور؟',
        'auth.signin': 'تسجيل الدخول',
        'auth.or': 'أو تابع من خلال',
        'auth.noaccount': 'ليس لديك حساب؟',
        'auth.createfree': 'أنشئ حساباً مجاناً',
        'auth.loginfailed': 'فشل تسجيل الدخول',

        // Auth - Register
        'auth.createaccount': 'أنشئ حسابك',
        'auth.almostthere': 'اقتربنا!',
        'auth.choosetype': 'اختر نوع حسابك لتبدأ',
        'auth.filldetails': 'أكمل بياناتك لإتمام التسجيل',
        'auth.role': 'الدور',
        'auth.account': 'الحساب',
        'auth.iwantto': 'أريد أن',
        'auth.iama': 'أنا',
        'auth.jobseeker': 'باحث عن عمل',
        'auth.jobseeker.desc': 'أبحث عن فرص عمل في مجال الأسنان',
        'auth.clinic': 'عيادة / صاحب عمل',
        'auth.clinic.desc': 'أبحث عن موظفين في مجال الأسنان',
        'auth.assistant': 'مساعد طبيب أسنان',
        'auth.assistant.desc': 'طاقم العيادة والمساعدين',
        'auth.salesrep': 'مندوب مبيعات',
        'auth.salesrep.desc': 'مبيعات معدات ومستلزمات الأسنان',
        'auth.dentalclinic': 'عيادة أسنان',
        'auth.dentalclinic.desc': 'عيادة تبحث عن موظفين',
        'auth.dentist': 'طبيب أسنان',
        'auth.dentist.desc': 'طبيب يبحث عن موظفين لعيادته',
        'auth.continue': 'متابعة',
        'auth.firstname': 'الاسم الأول',
        'auth.lastname': 'اسم العائلة',
        'auth.confirmpassword': 'تأكيد كلمة المرور',
        'auth.agreeto': 'أوافق على',
        'auth.terms': 'شروط الخدمة',
        'auth.and': 'و',
        'auth.privacy': 'سياسة الخصوصية',
        'auth.back': 'رجوع',
        'auth.createaccount.btn': 'إنشاء حساب',
        'auth.haveaccount': 'لديك حساب بالفعل؟',
        'auth.registerfailed': 'فشل التسجيل',

        // About Page
        'about.title': 'عن',
        'about.subtitle': 'نربط محترفي الأسنان الموهوبين بالعيادات الرائدة في المنطقة',
        'about.mission': 'مهمتنا',
        'about.mission.p1': 'Hire Me مكرسة لتغيير الطريقة التي يجد بها محترفو الأسنان وظائف أحلامهم وكيف تكتشف العيادات المواهب الاستثنائية.',
        'about.mission.p2': 'نؤمن بإنشاء اتصالات ذات معنى تفيد كل من الباحثين عن عمل وأصحاب العمل، مما يعزز النمو والتميز في مجال طب الأسنان.',
        'about.whyus': 'لماذا تختارنا؟',
        'about.whyus.1': 'منصة متخصصة لمحترفي الأسنان',
        'about.whyus.2': 'خوارزمية مطابقة ذكية',
        'about.whyus.3': 'عيادات ومرشحين موثقين',
        'about.whyus.4': 'عملية تقديم سهلة',
        'about.values': 'قيمنا',
        'about.community': 'المجتمع',
        'about.community.desc': 'بناء شبكة داعمة من محترفي الأسنان',
        'about.excellence': 'التميز',
        'about.excellence.desc': 'ملتزمون بأعلى معايير التوظيف',
        'about.trust': 'الثقة',
        'about.trust.desc': 'ملفات موثقة وعمليات شفافة',
        'about.cta': 'مستعد للبدء؟',
        'about.cta.desc': 'انضم لآلاف محترفي الأسنان والعيادات الذين يستخدمون Hire Me',
        'about.cta.btn': 'أنشئ حسابك',

        // Contact Page
        'contact.title': 'تواصل معنا',
        'contact.subtitle': 'هل لديك أسئلة؟ نحب أن نسمع منك',
        'contact.form.title': 'أرسل لنا رسالة',
        'contact.name': 'الاسم',
        'contact.name.placeholder': 'اسمك',
        'contact.email': 'البريد الإلكتروني',
        'contact.email.placeholder': 'بريدك@example.com',
        'contact.subject': 'الموضوع',
        'contact.subject.placeholder': 'كيف يمكننا مساعدتك؟',
        'contact.message': 'الرسالة',
        'contact.message.placeholder': 'أخبرنا المزيد...',
        'contact.send': 'إرسال الرسالة',
        'contact.info.title': 'معلومات التواصل',
        'contact.info.subtitle': 'تواصل معنا عبر أي من هذه القنوات وسنرد عليك في أقرب وقت ممكن.',
        'contact.phone': 'الهاتف',
        'contact.office': 'المكتب',
        'contact.help': 'تحتاج مساعدة فورية؟',
        'contact.help.desc': 'اطلع على قسم الأسئلة الشائعة للحصول على إجابات سريعة.',
        'contact.faq': 'عرض الأسئلة الشائعة',

        // Footer
        'footer.desc': 'نربط محترفي الأسنان بفرص العمل المثالية منذ 2020.',
        'footer.company': 'الشركة',
        'footer.aboutus': 'من نحن',
        'footer.careers': 'وظائف',
        'footer.press': 'الصحافة',
        'footer.blog': 'المدونة',
        'footer.forjobseekers': 'للباحثين عن عمل',
        'footer.browsejobs': 'تصفح الوظائف',
        'footer.createcv': 'إنشاء سيرة ذاتية',
        'footer.resources': 'مصادر مهنية',
        'footer.salary': 'دليل الرواتب',
        'footer.foremployers': 'لأصحاب العمل',
        'footer.postjob': 'نشر وظيفة',
        'footer.searchcandidates': 'البحث عن مرشحين',
        'footer.pricing': 'الأسعار',
        'footer.employerresources': 'مصادر أصحاب العمل',
        'footer.support': 'الدعم',
        'footer.helpcenter': 'مركز المساعدة',
        'footer.contactus': 'اتصل بنا',
        'footer.privacypolicy': 'سياسة الخصوصية',
        'footer.termsofservice': 'شروط الخدمة',
        'footer.copyright': 'Hire Me. جميع الحقوق محفوظة.',

        // Jobs Page
        'jobs.title': 'اعثر على وظيفة أسنان أحلامك',
        'jobs.subtitle': 'تصفح مئات الوظائف من أفضل العيادات',
        'jobs.search': 'ابحث عن وظائف...',
        'jobs.location': 'الموقع',
        'jobs.type': 'نوع الوظيفة',
        'jobs.fulltime': 'دوام كامل',
        'jobs.parttime': 'دوام جزئي',
        'jobs.contract': 'عقد',
        'jobs.apply': 'تقدم الآن',
        'jobs.save': 'حفظ الوظيفة',
        'jobs.posted': 'نُشرت',
        'jobs.daysago': 'يوم مضى',
        'jobs.noresults': 'لا توجد وظائف تطابق معاييرك',

        // Dashboard Common
        'dashboard.welcome': 'مرحباً بعودتك',
        'dashboard.welcomesubtitle': 'إليك ما يحدث في بحثك عن وظيفة',
        'dashboard.overview': 'نظرة عامة',
        'dashboard.recentactivity': 'النشاط الأخير',
        'dashboard.recentactivity.subtitle': 'آخر التفاعلات على ملفك الشخصي',
        'dashboard.viewall': 'عرض الكل',
        'dashboard.applications': 'الطلبات',
        'dashboard.messages': 'الرسائل',
        'dashboard.profile': 'الملف الشخصي',
        'dashboard.settings': 'الإعدادات',
        'dashboard.editcv': 'تعديل السيرة الذاتية',
        'dashboard.completecv': 'أكمل سيرتك الذاتية للحصول على مزيد من المطابقات',
        'dashboard.profilecomplete': 'ملفك مكتمل بنسبة',
        'dashboard.complete': 'مكتمل',
        'dashboard.completenow': 'أكمل الآن',
        'dashboard.profileviews': 'مشاهدات الملف',
        'dashboard.matchscore': 'نسبة التطابق',
        'dashboard.thisweek': 'هذا الأسبوع',
        'dashboard.yourmatchscore': 'نسبة تطابقك',
        'dashboard.matchdesc': 'ممتاز! ملفك يتطابق جيداً مع معظم متطلبات أصحاب العمل.',
        'dashboard.skills': 'المهارات',
        'dashboard.experience': 'الخبرة',
        'dashboard.location': 'الموقع',
        'dashboard.improvescore': 'تحسين النسبة',
        'dashboard.recommended': 'موصى به لك',
        'dashboard.recommended.subtitle': 'وظائف تتطابق مع ملفك',
        'dashboard.hoursago': 'ساعات مضت',
        'dashboard.dayago': 'يوم مضى',
        'dashboard.saved': 'وظائف محفوظة',

        // Sidebar
        'sidebar.dashboard': 'لوحة التحكم',
        'sidebar.cvbuilder': 'بناء السيرة الذاتية',
        'sidebar.myprofile': 'ملفي الشخصي',
        'sidebar.applications': 'طلباتي',
        'sidebar.applications.employer': 'طلبات المتقدمين',
        'sidebar.messages': 'الرسائل',
        'sidebar.settings': 'الإعدادات',
        'sidebar.findjobs': 'البحث عن وظائف',
        'sidebar.findcandidates': 'البحث عن مرشحين',
        'sidebar.jobpostings': 'الوظائف المنشورة',
        'sidebar.savedcandidates': 'المرشحين المحفوظين',
        'sidebar.clinicprofile': 'ملف العيادة',
        'sidebar.manageusers': 'إدارة المستخدمين',
        'sidebar.managecvs': 'إدارة السير الذاتية',
        'sidebar.manageclinics': 'إدارة العيادات',
        'sidebar.analytics': 'التحليلات',
        'sidebar.moderation': 'الإشراف',
        'sidebar.help': 'المساعدة والدعم',
        'sidebar.signout': 'تسجيل الخروج',

        // CV Builder
        'cv.title': 'بناء السيرة الذاتية',
        'cv.subtitle': 'أنشئ سيرتك الذاتية المهنية في دقائق',
        'cv.savedraft': 'حفظ المسودة',
        'cv.preview': 'معاينة',
        'cv.progress': 'التقدم',
        'cv.complete': 'مكتمل',
        'cv.previous': 'السابق',
        'cv.continue': 'متابعة',
        'cv.skip': 'تخطي',
        'cv.completecv': 'إكمال السيرة الذاتية',
        'cv.step': 'الخطوة',
        'cv.of': 'من',
        'cv.optional': 'اختياري',

        // CV Steps
        'cv.step.personal': 'المعلومات الشخصية',
        'cv.step.personal.desc': 'المعلومات الأساسية',
        'cv.step.experience': 'الخبرة',
        'cv.step.experience.desc': 'تاريخ العمل',
        'cv.step.skills': 'المهارات',
        'cv.step.skills.desc': 'قدراتك',
        'cv.step.certifications': 'الشهادات',
        'cv.step.certifications.desc': 'المؤهلات (اختياري)',
        'cv.step.languages': 'اللغات',
        'cv.step.languages.desc': 'اللغات المتحدثة',
        'cv.step.salary': 'الراتب',
        'cv.step.salary.desc': 'التوقعات',
        'cv.step.location': 'الموقع',
        'cv.step.location.desc': 'التفضيلات',
        'cv.step.availability': 'التوفر',
        'cv.step.availability.desc': 'الجدول',
        'cv.step.documents': 'المستندات',
        'cv.step.documents.desc': 'ملفات اختيارية (اختياري)',

        // Personal Info Form
        'cv.personal.intro': 'لنبدأ بمعلوماتك الأساسية. ستظهر هذه في أعلى سيرتك الذاتية.',
        'cv.personal.fullname': 'الاسم الكامل',
        'cv.personal.fullname.placeholder': 'أحمد محمد',
        'cv.personal.email': 'البريد الإلكتروني',
        'cv.personal.email.placeholder': 'ahmed@example.com',
        'cv.personal.phone': 'رقم الهاتف',
        'cv.personal.phone.placeholder': '+966 55 123 4567',
        'cv.personal.city': 'المدينة',
        'cv.personal.city.placeholder': 'الرياض',
        'cv.personal.gender': 'الجنس',
        'cv.personal.gender.select': 'اختر الجنس',
        'cv.personal.gender.male': 'ذكر',
        'cv.personal.gender.female': 'أنثى',
        'cv.personal.gender.other': 'آخر',
        'cv.personal.gender.prefer': 'أفضل عدم الإفصاح',
        'cv.personal.dob': 'تاريخ الميلاد',
        'cv.personal.address': 'العنوان',
        'cv.personal.address.placeholder': 'شارع الملك فهد 123',
        'cv.personal.nationality': 'الجنسية',
        'cv.personal.nationality.placeholder': 'سعودي',
        'cv.personal.bio': 'نبذة مهنية',
        'cv.personal.bio.placeholder': 'اكتب نبذة مختصرة عن نفسك، أهدافك المهنية، وما يجعلك مرشحاً مميزاً...',
        'cv.personal.photo': 'صورة الملف الشخصي',
        'cv.personal.upload': 'رفع صورة',
        'cv.personal.photoinfo': 'JPG، PNG أو WebP. أقصى حجم 2MB.',
        'cv.personal.tip': 'الملف الشخصي المكتمل مع صورة احترافية يزيد من فرصك في جذب انتباه أصحاب العمل.',
        'cv.personal.characters': 'حرف',

        // Experience Form
        'cv.exp.intro': 'أضف خبراتك العملية. ابدأ بأحدث وظيفة.',
        'cv.exp.add': 'إضافة خبرة عمل',
        'cv.exp.edit': 'تعديل الخبرة',
        'cv.exp.addnew': 'إضافة خبرة',
        'cv.exp.jobtitle': 'المسمى الوظيفي',
        'cv.exp.jobtitle.placeholder': 'مساعد طبيب أسنان',
        'cv.exp.company': 'الشركة',
        'cv.exp.company.placeholder': 'عيادة الابتسامة لطب الأسنان',
        'cv.exp.location': 'الموقع',
        'cv.exp.location.placeholder': 'الرياض، السعودية',
        'cv.exp.current': 'أعمل هنا حالياً',
        'cv.exp.startdate': 'تاريخ البدء',
        'cv.exp.enddate': 'تاريخ الانتهاء',
        'cv.exp.description': 'الوصف',
        'cv.exp.description.placeholder': 'صف مسؤولياتك وإنجازاتك...',
        'cv.exp.present': 'حتى الآن',
        'cv.exp.update': 'تحديث',
        'cv.exp.note': 'إضافة خبرة عمل واحدة على الأقل تساعد أصحاب العمل على فهم خلفيتك وتزيد من نسبة تطابقك.',

        // Skills Form
        'cv.skills.intro': 'اختر المهارات التي تتناسب مع خبراتك. أضف على الأقل 3 مهارات لتحسين نسبة تطابقك.',
        'cv.skills.selected': 'المهارات المختارة',
        'cv.skills.noselected': 'لم يتم اختيار مهارات بعد. اختر من الاقتراحات أدناه أو أضف مهاراتك الخاصة.',
        'cv.skills.addmore': 'أضف على الأقل {count} مهارة أخرى للمتابعة.',
        'cv.skills.search': 'البحث عن مهارات',
        'cv.skills.searchplaceholder': 'اكتب للبحث عن مهارات...',
        'cv.skills.addcustom': 'إضافة مهارة مخصصة',
        'cv.skills.customplaceholder': 'أدخل مهارة غير مدرجة أعلاه',
        'cv.skills.popular': 'مهارات طب الأسنان الشائعة',
        'cv.skills.allavailable': 'جميع المهارات المتاحة',

        // Common
        'common.loading': 'جاري التحميل...',
        'common.save': 'حفظ',
        'common.cancel': 'إلغاء',
        'common.delete': 'حذف',
        'common.edit': 'تعديل',
        'common.close': 'إغلاق',
        'common.search': 'بحث',
        'common.filter': 'تصفية',
        'common.viewmore': 'عرض المزيد',
        'common.learnmore': 'اعرف المزيد',
        'common.tip': 'نصيحة',
        'common.note': 'ملاحظة',
        'common.add': 'إضافة',
        // Admin Dashboard
        'admin.dashboard': 'لوحة تحكم المدير',
        'admin.subtitle': 'نظرة عامة على المنصة والإدارة',
        'admin.stats.users': 'إجمالي المستخدمين',
        'admin.stats.jobseekers': 'الباحثين عن عمل',
        'admin.stats.clinics': 'العيادات',
        'admin.stats.activecvs': 'السير الذاتية النشطة',
        'admin.recentusers': 'المستخدمين الجدد',
        'admin.recentusers.subtitle': 'أحدث التسجيلات بالمنصة',
        'admin.pending': 'طلبات معلقة',
        'admin.pending.subtitle': 'عناصر تحتاج للمراجعة',
        'admin.viewall': 'عرض الكل',
        'admin.viewallpending': 'عرض جميع المعلقة',
        'admin.matches': 'مطابقات هذا الشهر',
        'admin.activejobseekers': 'باحثين نشطين',
        'admin.newusers': 'مستخدمين جدد هذا الأسبوع',
        'admin.export': 'تصدير تقرير',
        'admin.adduser': 'إضافة مستخدم',
        'admin.table.user': 'المستخدم',
        'admin.table.type': 'النوع',
        'admin.table.status': 'الحالة',
        'admin.table.registered': 'تاريخ التسجيل',
        'admin.thismonth': 'هذا الشهر',

        // Admin Users Page
        'admin.users.title': 'إدارة المستخدمين',
        'admin.users.subtitle': 'إدارة جميع المستخدمين، توثيق الحسابات، ومراجعة المستندات.',
        'admin.users.export': 'تصدير',
        'admin.users.add': 'إضافة مستخدم',
        'admin.users.search': 'بحث بالاسم أو البريد الإلكتروني...',
        'admin.users.filter.role': 'جميع الأدوار',
        'admin.users.filter.jobseeker': 'احثين عن عمل',
        'admin.users.filter.clinic': 'عيادات',
        'admin.users.filter.admin': 'مدراء',
        'admin.users.filter.status': 'جميع الحالات',
        'admin.users.filter.verified': 'موثق',
        'admin.users.filter.unverified': 'غير موثق',
        'admin.users.table.user': 'المستخدم',
        'admin.users.table.role': 'الدور',
        'admin.users.table.verification': 'التوثيق',
        'admin.users.table.docs': 'المستندات',
        'admin.users.table.joined': 'تاريخ الانضمام',
        'admin.users.table.actions': 'إجراءات',
        'admin.users.docs.review': 'مراجعة',
        'admin.users.docs.title': 'المستندات',
        'admin.users.docs.no_docs': 'لا توجد مستندات مرفوعة من هذا المستخدم.',
        'admin.users.docs.view': 'عرض',
        'admin.users.docs.approve': 'الموافقة وتوثيق المستخدم',
        'admin.users.delete.confirm': 'هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
        'admin.users.delete.error': 'فشل حذف المستخدم',
        'admin.users.verify.error': 'خطأ في تحديث التوثيق',
        'admin.users.loading': 'جاري تحميل المستخدمين...',
        'admin.users.nousers': 'لم يتم العثور على مستخدمين.',
        'admin.users.permission_denied': 'تم رفض الصلاحية. يرجى تسجيل الخروج وتسجيل الدخول مرة أخرى لتحديث صلاحيات الأدمن.',
    },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    // Use lazy initializer to read from localStorage on first render
    const [language, setLanguageState] = useState<Language>('ar');
    const [mounted, setMounted] = useState(false);

    // Load language from localStorage on mount (client-side only)
    useEffect(() => {
        const saved = localStorage.getItem('language') as Language;
        if (saved && (saved === 'en' || saved === 'ar')) {
            setLanguageState(saved);
        }
        setMounted(true);
    }, []);

    // Update document direction and lang when language changes
    useEffect(() => {
        if (mounted) {
            document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
            document.documentElement.lang = language;
        }
    }, [language, mounted]);

    const setLanguage = (lang: Language) => {
        if (lang !== 'en' && lang !== 'ar') {
            console.warn('Invalid language:', lang);
            return;
        }
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        if (!translations[language]) {
            console.warn(`Missing translations for language: ${language}`);
            return key;
        }
        return translations[language][key as keyof typeof translations.en] || key;
    };

    // Prevent hydration mismatch by showing nothing until mounted
    if (!mounted) {
        return (
            <LanguageContext.Provider value={{ language: 'ar', setLanguage, t: (key) => translations.ar[key as keyof typeof translations.ar] || key }}>
                {children}
            </LanguageContext.Provider>
        );
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}
