import { useState, useMemo } from 'react';
import { useClinic } from '../context/ClinicContext';
import { useAuth } from '../context/AuthContext';
import { Layout } from '../components/ui/Layout';
import { Modal } from '../components/ui/Modal';
import { haptic } from '../lib/haptics';
import { TaskPriority } from '../types';
import { format, parseISO, isToday } from 'date-fns';
import { ar } from 'date-fns/locale';
import {
  Plus, CheckCircle2, Circle, Clock, AlertTriangle,
  ClipboardList, Trash2, User, Calendar as CalendarIcon,
  ChevronDown, Sparkles, Flag, Wrench, ChevronUp, Package
} from 'lucide-react';
import { findTreatmentPrep, generatePrepTaskDescription } from '../lib/treatmentPrep';

const PRIORITY_CONFIG: Record<TaskPriority, { label: string; color: string; bg: string; border: string; icon: typeof AlertTriangle }> = {
  urgent: { label: 'عاجل', color: '#ef4444', bg: '#fef2f2', border: '#fecaca', icon: AlertTriangle },
  normal: { label: 'عادي', color: '#f59e0b', bg: '#fffbeb', border: '#fde68a', icon: Flag },
  low: { label: 'منخفض', color: '#6b7280', bg: '#f9fafb', border: '#e5e7eb', icon: Clock },
};

export function Tasks() {
  const { tasks, addTask, completeTask, deleteTask, patients, appointments, treatments, assistantAssignments } = useClinic();
  const { currentUser, hasPermission, users } = useAuth();

  const canManage = hasPermission('manage_tasks');
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [showCompleted, setShowCompleted] = useState(false);
  const [expandedPrepTask, setExpandedPrepTask] = useState<string | null>(null);

  // ── Auto-Generated Preparation Tasks ──
  // Find which doctor this assistant is assigned to
  const autoGeneratedTasks = useMemo(() => {
    if (!currentUser) return [];
    
    // Find assignment for the current user (works for secretaries/assistants)
    const myAssignment = assistantAssignments.find(a => a.assistantUserId === currentUser.id);
    
    // If user is a doctor, show prep tasks for their own appointments
    // If user is an assistant, show prep tasks for their assigned doctor
    // If user is admin, show all prep tasks
    let targetDoctorIds: string[] = [];
    
    if (currentUser.role === 'admin') {
      // Admin sees all doctors' prep tasks
      targetDoctorIds = Array.from(new Set(appointments.map(a => a.doctorId)));
    } else if (currentUser.role === 'doctor') {
      targetDoctorIds = [currentUser.id];
    } else if (myAssignment) {
      targetDoctorIds = [myAssignment.doctorUserId];
    }
    
    if (targetDoctorIds.length === 0) return [];
    
    const today = new Date().toISOString().split('T')[0];
    
    // Get today's scheduled appointments for the target doctors
    const todayAppointments = appointments.filter(apt => 
      apt.date === today && 
      apt.status === 'scheduled' && 
      targetDoctorIds.includes(apt.doctorId)
    );
    
    // Generate prep tasks for each appointment
    return todayAppointments
      .map(apt => {
        const prep = findTreatmentPrep(apt.treatment);
        if (!prep) return null;
        
        const { title, description } = generatePrepTaskDescription(
          apt.patientName,
          apt.treatment,
          apt.time,
          prep
        );
        
        return {
          id: `auto-${apt.id}`,
          appointmentId: apt.id,
          doctorName: apt.doctorName,
          doctorId: apt.doctorId,
          patientName: apt.patientName,
          time: apt.time,
          treatment: apt.treatment,
          title,
          description,
          prep,
        };
      })
      .filter(Boolean) as Array<{
        id: string;
        appointmentId: string;
        doctorName: string;
        doctorId: string;
        patientName: string;
        time: string;
        treatment: string;
        title: string;
        description: string;
        prep: ReturnType<typeof findTreatmentPrep> & {};
      }>;
  }, [currentUser, assistantAssignments, appointments]);

  // Create task form state
  const [newTitle, setNewTitle] = useState('');
  const [newPriority, setNewPriority] = useState<TaskPriority>('normal');
  const [newAssignedTo, setNewAssignedTo] = useState('');
  const [newDueDate, setNewDueDate] = useState(new Date().toISOString().split('T')[0]);

  // Dynamic Smart Suggestions
  const dynamicSuggestions = useMemo(() => {
    const suggestions: Array<{ title: string; priority: TaskPriority }> = [];
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    const tomorrowStr = tomorrow.toISOString().split('T')[0];

    // Follow up missed/scheduled appointments for tomorrow
    const tomorrowAppts = appointments.filter(a => a.date === tomorrowStr && a.status === 'scheduled');
    if (tomorrowAppts.length > 0) {
      suggestions.push({
        title: `تأكيد مواعيد الغد (${tomorrowAppts.length} مرضى)`,
        priority: 'urgent',
      });
    }

    // Check active treatments (ortho/implant usually need specific prep)
    const hasImplants = treatments.some(t => t.name.includes('زراعة') || t.name.includes('implant'));
    if (hasImplants) {
      suggestions.push({ title: 'تجهيز أدوات ومواد الزراعة', priority: 'urgent' });
    }

    // Default suggestions based on common clinic needs
    suggestions.push(
      { title: 'تعقيم أدوات العيادة', priority: 'urgent' },
      { title: 'جرد المواد والنواقص', priority: 'normal' }
    );

    return suggestions;
  }, [appointments, treatments]);

  // Get assignable users (secretaries + accountants)
  const assignableUsers = useMemo(() =>
    users.filter(u => u.isActive && (u.role === 'secretary' || u.role === 'accountant')),
    [users]
  );

  // Filter tasks for the current user
  const myTasks = useMemo(() => {
    let filtered = tasks;
    // If not admin/doctor, only show tasks assigned to this user
    if (!canManage) {
      filtered = filtered.filter(t => t.assignedToUserId === currentUser?.id);
    }
    // Sort: urgent first, then by due date
    return filtered.sort((a, b) => {
      if (a.status !== b.status) return a.status === 'pending' ? -1 : 1;
      const pOrder: Record<TaskPriority, number> = { urgent: 0, normal: 1, low: 2 };
      if (pOrder[a.priority] !== pOrder[b.priority]) return pOrder[a.priority] - pOrder[b.priority];
      return new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime();
    });
  }, [tasks, canManage, currentUser]);

  const pendingTasks = myTasks.filter(t => t.status === 'pending');
  const completedTasks = myTasks.filter(t => t.status === 'completed');
  const todayCompleted = completedTasks.filter(t => t.completedAt && isToday(parseISO(t.completedAt))).length;

  const handleCreateTask = () => {
    if (!newTitle.trim() || !newAssignedTo) {
      haptic.error();
      return;
    }
    haptic.success();
    addTask({
      title: newTitle.trim(),
      priority: newPriority,
      assignedToUserId: newAssignedTo,
      createdByUserId: currentUser?.id || '',
      dueDate: newDueDate,
    });
    // Reset form
    setNewTitle('');
    setNewPriority('normal');
    setNewAssignedTo('');
    setNewDueDate(new Date().toISOString().split('T')[0]);
    setIsCreateModalOpen(false);
  };

  const getAssigneeName = (userId: string) => {
    const user = users.find(u => u.id === userId);
    return user?.displayName || 'غير محدد';
  };

  const getCreatorName = (userId: string) => {
    const user = users.find(u => u.id === userId);
    return user?.displayName || 'غير محدد';
  };

  return (
    <Layout title="المهام" subtitle={canManage ? 'إدارة المهام' : 'مهامي اليومية'}>
      <div className="space-y-4 pb-8">

        {/* Stats Bar */}
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-white rounded-2xl border border-slate-200 p-4 flex flex-col items-center shadow-sm">
            <span className="text-2xl font-black text-amber-500 mb-1">{pendingTasks.length}</span>
            <span className="text-xs font-bold text-slate-600">قيد التنفيذ</span>
          </div>
          <div className="bg-white rounded-2xl border border-slate-200 p-4 flex flex-col items-center shadow-sm">
            <span className="text-2xl font-black text-emerald-500 mb-1">{todayCompleted}</span>
            <span className="text-xs font-bold text-slate-600">أُنجزت اليوم</span>
          </div>
        </div>

        {/* ═══ Auto-Generated Prep Tasks ═══ */}
        {autoGeneratedTasks.length > 0 && (
          <div>
            <div className="flex items-center gap-2 mb-2.5">
              <div className="flex items-center gap-1.5 px-3 py-1.5 bg-gradient-to-r from-violet-500 to-purple-600 text-white rounded-xl">
                <Wrench className="w-4 h-4" />
                <span className="text-[12px] font-bold">مهام تحضير اليوم</span>
              </div>
              <span className="text-[11px] font-bold text-slate-400 bg-slate-100 px-2 py-0.5 rounded-lg">
                {autoGeneratedTasks.length} مهمة
              </span>
            </div>
            <div className="space-y-2.5">
              {autoGeneratedTasks.map(task => {
                const isExpanded = expandedPrepTask === task.id;
                return (
                  <div
                    key={task.id}
                    className="bg-white rounded-2xl border border-violet-100 shadow-sm overflow-hidden transition-all"
                    style={{ borderRightWidth: '4px', borderRightColor: '#8b5cf6' }}
                  >
                    {/* Task Header */}
                    <button
                      onClick={() => {
                        haptic.light();
                        setExpandedPrepTask(isExpanded ? null : task.id);
                      }}
                      className="w-full p-3.5 flex items-start gap-3 text-right active:bg-violet-50/50 transition-colors"
                    >
                      <div className="w-9 h-9 rounded-xl bg-violet-100 text-violet-600 flex items-center justify-center shrink-0 mt-0.5 text-[16px]">
                        {task.prep.emoji}
                      </div>
                      <div className="flex-1 min-w-0">
                        <h3 className="text-[13px] font-bold text-slate-800 leading-snug">
                          {task.prep.emoji} {task.prep.label}
                        </h3>
                        <div className="flex items-center gap-2 mt-1.5 text-[11px] text-slate-500">
                          <span className="font-bold text-violet-500">{task.patientName}</span>
                          <span className="text-slate-300">·</span>
                          <span className="flex items-center gap-1">
                            <Clock className="w-3 h-3" />
                            {task.time}
                          </span>
                          <span className="text-slate-300">·</span>
                          <span className="text-slate-400 font-medium">{task.doctorName}</span>
                        </div>
                      </div>
                      <div className="shrink-0 mt-1">
                        {isExpanded ? (
                          <ChevronUp className="w-4 h-4 text-violet-400" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-slate-400" />
                        )}
                      </div>
                    </button>

                    {/* Expanded Details */}
                    {isExpanded && (
                      <div className="px-4 pb-4 animate-in slide-in-from-top-2 duration-200">
                        <div className="border-t border-violet-100 pt-3 space-y-3">
                          {/* Tools */}
                          <div className="bg-slate-50 rounded-xl p-3">
                            <h4 className="text-[11px] font-bold text-slate-600 mb-2 flex items-center gap-1.5">
                              <Wrench className="w-3.5 h-3.5 text-violet-500" />
                              الأدوات المطلوبة
                            </h4>
                            <ul className="space-y-1.5">
                              {task.prep.tools.map((tool, i) => (
                                <li key={i} className="text-[12px] text-slate-600 flex items-start gap-2 leading-relaxed">
                                  <span className="text-violet-400 mt-0.5 shrink-0">•</span>
                                  {tool}
                                </li>
                              ))}
                            </ul>
                          </div>

                          {/* Materials */}
                          <div className="bg-amber-50/60 rounded-xl p-3">
                            <h4 className="text-[11px] font-bold text-slate-600 mb-2 flex items-center gap-1.5">
                              <Package className="w-3.5 h-3.5 text-amber-500" />
                              المواد المطلوبة
                            </h4>
                            <ul className="space-y-1.5">
                              {task.prep.materials.map((mat, i) => (
                                <li key={i} className="text-[12px] text-slate-600 flex items-start gap-2 leading-relaxed">
                                  <span className="text-amber-400 mt-0.5 shrink-0">•</span>
                                  {mat}
                                </li>
                              ))}
                            </ul>
                          </div>

                          {/* Notes */}
                          {task.prep.notes && (
                            <div className="bg-red-50/60 rounded-xl p-3 flex items-start gap-2">
                              <AlertTriangle className="w-3.5 h-3.5 text-red-400 shrink-0 mt-0.5" />
                              <p className="text-[11px] text-red-600 font-medium leading-relaxed">{task.prep.notes}</p>
                            </div>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Pending Tasks */}
        {pendingTasks.length > 0 ? (
          <div className="space-y-2">
            {pendingTasks.map(task => {
              const pCfg = PRIORITY_CONFIG[task.priority];
              const PIcon = pCfg.icon;
              const isDueToday = isToday(parseISO(task.dueDate));
              const assigneeName = getAssigneeName(task.assignedToUserId);

              return (
                <div
                  key={task.id}
                  className="bg-white rounded-2xl border shadow-sm overflow-hidden active:scale-[0.99] transition-all"
                  style={{ borderColor: pCfg.border, borderRightWidth: '4px', borderRightColor: pCfg.color }}
                >
                  <div className="p-3.5 flex items-start gap-3">
                    {/* Completion Toggle */}
                    <button
                      onClick={() => { haptic.success(); completeTask(task.id); }}
                      className="mt-0.5 shrink-0 w-7 h-7 rounded-full border-2 flex items-center justify-center transition-all active:scale-90 hover:bg-emerald-50"
                      style={{ borderColor: pCfg.color }}
                      title="إكمال المهمة"
                    >
                      <Circle className="w-4 h-4" style={{ color: pCfg.color }} />
                    </button>

                    {/* Task Content */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-2 mb-1.5">
                        <div className="flex items-center gap-1.5">
                          <h3 className="text-[14px] font-bold text-slate-800 leading-snug">{task.title}</h3>
                        </div>
                        {canManage && (
                          <button
                            onClick={() => { if (confirm('حذف هذه المهمة؟')) { haptic.medium(); deleteTask(task.id); } }}
                            className="shrink-0 w-6 h-6 rounded-lg flex items-center justify-center text-slate-400 hover:text-red-500 hover:bg-red-50 transition-all"
                            title="حذف المهمة"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        )}
                      </div>

                      {task.description && (
                        <p className="text-[12px] text-slate-500 mb-2 leading-relaxed line-clamp-2">{task.description}</p>
                      )}

                      <div className="flex items-center gap-3 mt-1.5 text-[11px] font-bold text-slate-400">
                        {canManage && (
                          <span className="flex items-center gap-1 text-slate-600 bg-slate-100 px-1.5 py-0.5 rounded-md">
                            <User className="w-3 h-3" /> {assigneeName}
                          </span>
                        )}
                        <span className={`flex items-center gap-1 ${isDueToday ? 'text-blue-500' : ''}`}>
                          <CalendarIcon className="w-3 h-3" />
                          {isDueToday ? 'اليوم' : format(parseISO(task.dueDate), 'dd MMM', { locale: ar })}
                        </span>
                        {task.priority === 'urgent' && (
                          <span className="flex items-center gap-1 text-red-500">
                            <AlertTriangle className="w-3 h-3" />
                            عاجل
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="bg-white rounded-2xl border border-slate-200 p-8 flex flex-col items-center justify-center text-center shadow-sm">
            <div className="w-16 h-16 rounded-full bg-emerald-50 flex items-center justify-center mb-3">
              <CheckCircle2 className="w-8 h-8 text-emerald-500" />
            </div>
            <h3 className="text-[15px] font-bold text-slate-700 mb-1">لا توجد مهام معلّقة</h3>
            <p className="text-xs text-slate-400">
              {canManage ? 'اضغط + لإضافة مهمة جديدة' : 'أحسنت! تم إنجاز جميع المهام 🎉'}
            </p>
          </div>
        )}

        {/* Completed Tasks Section */}
        {completedTasks.length > 0 && (
          <div>
            <button
              onClick={() => setShowCompleted(!showCompleted)}
              className="w-full flex items-center justify-between py-2.5 px-3 rounded-xl bg-emerald-50/50 border border-emerald-100 text-[12px] font-bold text-emerald-600 active:scale-[0.98] transition-all mb-2"
            >
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4" />
                المهام المنجزة ({completedTasks.length})
              </span>
              <ChevronDown className={`w-4 h-4 transition-transform ${showCompleted ? 'rotate-180' : ''}`} />
            </button>

            {showCompleted && (
              <div className="space-y-1.5">
                {completedTasks.map(task => (
                  <div key={task.id} className="bg-slate-50 rounded-xl border border-slate-200 p-3 flex items-center gap-3 opacity-70">
                    <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-[13px] font-medium text-slate-500 line-through">{task.title}</p>
                      <div className="flex items-center gap-2 mt-0.5">
                        <span className="text-[10px] text-slate-400">
                          {task.completedAt && format(parseISO(task.completedAt), 'dd/MM HH:mm', { locale: ar })}
                        </span>
                        {canManage && (
                          <span className="text-[10px] text-indigo-400 font-medium">
                            {getAssigneeName(task.assignedToUserId)}
                          </span>
                        )}
                      </div>
                    </div>
                    {canManage && (
                      <button
                        onClick={() => { haptic.light(); deleteTask(task.id); }}
                        className="shrink-0 w-6 h-6 rounded-lg flex items-center justify-center text-slate-300 hover:text-red-400 transition-all"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Create Task Modal */}
      <Modal isOpen={isCreateModalOpen} onClose={() => setIsCreateModalOpen(false)} title="إضافة مهمة جديدة">
        <div className="space-y-4">
          {/* Smart Suggestions */}
          <div className="flex gap-2 overflow-x-auto hide-scrollbar pb-2">
            {dynamicSuggestions.map((sug, idx) => (
              <button
                key={idx}
                type="button"
                onClick={() => {
                  setNewTitle(sug.title);
                  setNewPriority(sug.priority);
                  haptic.light();
                }}
                className="shrink-0 px-3 py-1.5 rounded-full bg-teal-50 text-teal-700 border border-teal-100 text-[11px] font-bold active:scale-95 transition-all flex items-center gap-1.5 hover:bg-teal-100"
              >
                <Sparkles className="w-3 h-3 text-teal-500" />
                {sug.title}
              </button>
            ))}
          </div>

          {/* Title */}
          <div>
            <label className="text-[11px] font-bold text-slate-500 mb-1.5 block">عنوان المهمة *</label>
            <input
              type="text"
              value={newTitle}
              onChange={e => setNewTitle(e.target.value)}
              placeholder="ما هي المهمة المطلوب إنجازها؟..."
              className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-[14px] font-bold text-slate-800 outline-none focus:bg-white focus:border-teal-500 transition-all"
            />
          </div>

          {/* Assign To & Due Date Row */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-[11px] font-bold text-slate-500 mb-1.5 block">إلى من؟ *</label>
              <select
                value={newAssignedTo}
                onChange={e => setNewAssignedTo(e.target.value)}
                className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-[13px] font-bold text-slate-800 outline-none focus:bg-white focus:border-teal-500 transition-all"
              >
                <option value="" disabled>-- اختر موظف --</option>
                {assignableUsers.map(u => (
                  <option key={u.id} value={u.id}>{u.displayName}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="text-[11px] font-bold text-slate-500 mb-1.5 block">متى التجهيز؟</label>
              <input
                type="date"
                value={newDueDate}
                onChange={e => setNewDueDate(e.target.value)}
                className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl text-[13px] font-bold text-slate-800 outline-none focus:bg-white focus:border-teal-500 transition-all"
              />
            </div>
          </div>

          {/* Priority block */}
          <div className="bg-slate-50 border border-slate-100 rounded-xl p-3">
            <label className="text-[10px] font-bold text-slate-400 mb-2 block uppercase tracking-wider">مستوى الأهمية</label>
            <div className="flex bg-white rounded-lg p-1 border border-slate-200 shadow-sm">
              {(Object.entries(PRIORITY_CONFIG) as [TaskPriority, typeof PRIORITY_CONFIG['urgent']][]).map(([key, cfg]) => (
                <button
                  key={key}
                  type="button"
                  onClick={() => setNewPriority(key as TaskPriority)}
                  className={`flex-1 flex items-center justify-center gap-1.5 py-1.5 rounded-md text-[11px] font-bold transition-all ${
                    newPriority === key
                      ? 'bg-slate-800 text-white shadow'
                      : 'bg-transparent text-slate-500 hover:bg-slate-100'
                  }`}
                >
                  <cfg.icon className="w-3.5 h-3.5" />
                  {cfg.label}
                </button>
              ))}
            </div>
          </div>

          {/* Submit */}
          <button
            onClick={handleCreateTask}
            disabled={!newTitle.trim() || !newAssignedTo}
            className="w-full flex items-center justify-center gap-2 bg-slate-900 text-white py-3.5 rounded-xl font-bold text-[14px] shadow-lg shadow-slate-200 disabled:opacity-40 disabled:cursor-not-allowed active:scale-[0.98] transition-all mt-2"
          >
            <Plus className="w-5 h-5" />
            حفظ المهمة الموكلة
          </button>
        </div>
      </Modal>

      {/* Floating Add Button (admin/doctor only) */}
      {canManage && (
        <button
          onClick={() => { haptic.medium(); setIsCreateModalOpen(true); }}
          className="fixed bottom-20 left-5 z-40 w-14 h-14 rounded-full bg-teal-600 text-white shadow-xl shadow-teal-300/40 flex items-center justify-center active:scale-90 transition-all hover:bg-teal-700"
        >
          <Plus className="w-7 h-7" />
        </button>
      )}
    </Layout>
  );
}
